import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

const faqs = [
  {
    question: 'How does the AI note summarization work?',
    answer: 'StudyMate AI uses advanced natural language processing to read your uploaded documents or text. It identifies the core concepts, filters out fluff, and structure the information into easily digestible bullet points and hierarchies.'
  },
  {
    question: 'What file formats do you support?',
    answer: 'Currently, we support PDF, DOCX, TXT, and direct text input. We are actively working on adding support for video and audio lecture transcription and summarization.'
  },
  {
    question: 'Can I export my flashcards to Anki?',
    answer: 'Yes! All flashcards generated by StudyMate AI can be exported as .apkg files which can be directly imported into Anki, complete with tags and formatting.'
  },
  {
    question: 'Is my data private and secure?',
    answer: 'Absolutely. We use enterprise-grade encryption for all your uploads. Your documents are only used to generate your study materials and are never used to train our base AI models without your explicit consent.'
  },
  {
    question: 'Do you offer a discount for students?',
    answer: 'Yes, we offer a 50% discount on the Pro plan for users who sign up with a valid .edu email address. The discount is applied automatically at checkout.'
  }
];

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section className="py-24 relative bg-slate-900/30">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-sm font-bold tracking-widest text-blue-500 uppercase mb-3">Got Questions?</h2>
          <h3 className="text-3xl md:text-5xl font-bold mb-6">Frequently Asked <span className="text-gradient">Questions</span></h3>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div 
              key={index} 
              className={`glass-card rounded-2xl overflow-hidden transition-all duration-300 ${openIndex === index ? 'border-blue-500/30 bg-navy-800/60' : 'hover:bg-navy-800/50'}`}
            >
              <button
                className="w-full px-6 py-5 flex items-center justify-between text-left focus:outline-none"
                onClick={() => setOpenIndex(openIndex === index ? -1 : index)}
              >
                <span className="font-semibold text-white text-lg">{faq.question}</span>
                {openIndex === index ? (
                  <ChevronUp className="w-5 h-5 text-blue-400 shrink-0" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-slate-400 shrink-0" />
                )}
              </button>
              
              <div 
                className={`px-6 overflow-hidden transition-all duration-300 ${openIndex === index ? 'max-h-48 pb-5 opacity-100' : 'max-h-0 opacity-0'}`}
              >
                <p className="text-slate-400 leading-relaxed">
                  {faq.answer}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
