import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { motion } from 'framer-motion';

const containerVariants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.1
    }
  }
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { 
    opacity: 1, 
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" }
  }
};

const faqs = [
  {
    question: 'How does the AI note summarization work?',
    answer: 'StudyMate AI uses advanced natural language processing to read your uploaded documents or text. It identifies the core concepts, filters out fluff, and structure the information into easily digestible bullet points and hierarchies.'
  },
  {
    question: 'What file formats do you support?',
    answer: 'Currently, we support PDF, DOCX, TXT, and direct text input. We are actively working on adding support for video and audio lecture transcription and summarization.'
  },
  {
    question: 'Can I export my flashcards to Anki?',
    answer: 'Yes! All flashcards generated by StudyMate AI can be exported as .apkg files which can be directly imported into Anki, complete with tags and formatting.'
  },
  {
    question: 'Is my data private and secure?',
    answer: 'Absolutely. We use enterprise-grade encryption for all your uploads. Your documents are only used to generate your study materials and are never used to train our base AI models without your explicit consent.'
  },
  {
    question: 'Do you offer a discount for students?',
    answer: 'Yes, we offer a 50% discount on the Pro plan for users who sign up with a valid .edu email address. The discount is applied automatically at checkout.'
  }
];

const FAQ = () => {
  // Track the index of the currently expanded FAQ item; -1 means all items are collapsed
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section className="py-24 relative bg-slate-50/50 dark:bg-slate-900/30">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-sm font-bold tracking-widest text-blue-500 uppercase mb-3">Got Questions?</h2>
          <h3 className="text-3xl md:text-5xl font-bold mb-6">Frequently Asked <span className="text-gradient">Questions</span></h3>
        </motion.div>

        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="space-y-4"
        >
          {faqs.map((faq, index) => (
            <motion.div 
              key={index} 
              variants={itemVariants}
              className={`glass-card rounded-2xl overflow-hidden transition-all duration-300 ${openIndex === index ? 'border-blue-500/30 bg-white dark:bg-navy-800/60' : 'hover:bg-white/80 dark:hover:bg-navy-800/50'}`}
            >
              <button
                className="w-full px-6 py-5 flex items-center justify-between text-left focus:outline-none"
                // Toggle expansion state: if clicked item is already open, collapse all (-1); otherwise set to this index
                onClick={() => setOpenIndex(openIndex === index ? -1 : index)}
              >
                <span className="font-semibold text-slate-900 dark:text-white text-lg">{faq.question}</span>
                {openIndex === index ? (
                  <ChevronUp className="w-5 h-5 text-blue-400 shrink-0" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-slate-400 shrink-0" />
                )}
              </button>
              
              {/* Animated accordion height expansion smoothly using Framer Motion */}
              <motion.div 
                initial={false}
                animate={{ height: openIndex === index ? 'auto' : 0, opacity: openIndex === index ? 1 : 0 }}
                transition={{ duration: 0.25, ease: 'easeInOut' }}
                className="px-6 overflow-hidden"
              >
                <p className="text-slate-600 dark:text-slate-400 leading-relaxed pb-5">
                  {faq.answer}
                </p>
              </motion.div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default FAQ;
